name: Build and run tests

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        dotnet: [6.0.401]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.203
    - name: Restore .NET local tools
      run: dotnet tool restore
    - name: Build and test
      run: dotnet fsi build.fsx
