name: Build and run tests

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        dotnet: [8.0.408]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.408
    - name: Restore .NET local tools
      run: dotnet tool restore
    - name: Build and test
      run: dotnet fsi build.fsx
